### PR TITLE
Fix issue #2: recipe page

### LINKED ISSUE #2: Page `/`
Afficher la liste des recettes disponibles

### PR DESCRIPTION
**Pull request by tibo-mllr**
# Issue

This closes #2 

# Description

Make the default page display all the recipes, with some information about them

### CODE REVIEW

File: src/lib/types/gourmet.d.ts [hunk 1]
```diff
@@ -0,0 +1,2552 @@
+/* eslint-disable */
```
Comment (Ishirui) [inline src/lib/types/gourmet.d.ts:1]: Remove

File: src/app/layout.tsx [hunk 2]
```diff
@@ -15,8 +15,8 @@ const geistMono = Geist_Mono({
 });
 
 export const metadata: Metadata = {
-  title: "Create Next App",
-  description: "Generated by create next app",
+  title: "Recipes",
```
Comment (Ishirui) [inline src/app/layout.tsx:18]:
```suggestion
  title: "Sigma Cooking",
```

**Review by Ishirui — APPROVED** [review]

**Review by Ishirui — APPROVED** [review]
